# Generated by Django 3.2.18 on 2023-05-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_recommendactors_recommendgenres_recommendkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendactors',
            name='movie_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendactors',
            name='origin',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendactors',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendgenres',
            name='movie_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendgenres',
            name='origin',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendgenres',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendkeyword',
            name='movie_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendkeyword',
            name='origin',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendkeyword',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
