# Generated by Django 3.2.18 on 2023-05-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20230520_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendactors',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recommendgenres',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recommendkeyword',
            name='score',
            field=models.FloatField(),
        ),
    ]
